name: before_doom
description: "A countdown and tracker for Avengers: Doomsday."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/marvel_watchlist.json
    - assets/images/
